Simply 3938/refactor custom list search updated
NYPL-Simplified/circulation-web pull request #371
Opened 2021-11-18 22:05 UTC by oliviawongnyc

## Description

- Refactored the `CustomListSearch` component to bring it up-to-date with current best practices. 
- Added `CustomListSearchFormContent` and `CustomListSearchAdvancedOptions` to make all components smaller/more manageable.
- Added/edited tests where needed.

## Motivation and Context

- This refactor is part of the larger List Manager refactor ([TAD](https://docs.google.com/document/d/1QhlTh9FLUAWJC9BcmSDgu7m972xyaBoHh1wcgnorq2o/edit)), which is being undertaken to make the code more up-to-date, simpler, and easier to read and maintain.

## How Has This Been Tested?

- I have adjusted and added tests where necessary, and all unit tests are passing.
- I tested search functionality on localhost.

## Checklist:

- [ x ] I have updated the documentation accordingly.
- [ x ] All new and existing tests passed.

2021-11-23 21:06 UTC, EdwinGuzman commented on tslint.json
> +  "extends": ["tslint-react-a11y"],
From 4 to 2 spaces? 👍

2021-11-23 21:16 UTC, EdwinGuzman commented on src/components/CustomListSearch.tsx
> +    startingTitle ? startingTitle : ""
Set `startingTitle` on line 19 to `""`. That way, it's the default and you can do `React.useState(startingTitle)` here.

2021-11-23 21:17 UTC, EdwinGuzman commented on src/components/CustomListSearch.tsx
> +    "All"
You might be able to set this to a specific type since you all the possible entrypoint values.

2021-11-23 21:18 UTC, EdwinGuzman commented on src/components/CustomListSearch.tsx
> +    "All"
By that I mean an enum or type instead of "All". Maybe something like `Entrypoints.All`. This might not make much sense here so don't worry if it doesn't make too much sense.

2021-11-24 06:13 UTC, samanthaandrews requested changes
Just one small thing, otherwise this looks great.

2021-11-24 06:13 UTC, samanthaandrews commented on src/components/CustomListSearchAdvancedOptions.tsx
> +            {Object.keys(sortByOptions).map((x) => (
Let's rename `x` to something more descriptive

2021-11-29 22:30 UTC, EdwinGuzman commented on src/components/CustomListSearchAdvancedOptions.tsx
> +  );
`.map` returns a new array, so I don't think you need the `[].concat` to begin with. Maybe just `languageFields?.map(....)` is enough. If not, maybe `[...languageFields?.map(...)]`.

2021-11-29 22:33 UTC, EdwinGuzman commented on src/components/CustomListSearchAdvancedOptions.tsx
> +            {/* eslint-disable-next-line jsx-a11y/no-onchange */}
Is this line here because of the `aria-selected` attribute on line 85?

2021-11-29 22:35 UTC, EdwinGuzman commented on src/components/CustomListSearchFormContent.tsx
> +              {!entryPoints.includes("All") && (
This was confusing before and a comment would make it clear that we _always_ want to displays the "All" option even if it's not selected on the backend.

2021-11-29 22:52 UTC, EdwinGuzman commented on src/components/__tests__/CustomListSearchAdvancedOptions-test.tsx
> +});
I think this is a great start but you should also test the two `set` functions that are passed instead of what gets displayed.
If the Sinon stub is not enough, there can be a variable `language` that is set to an empty string and you can pass a function for `setSelectedLanguage` that updates the `language` variable.

2021-11-29 22:54 UTC, EdwinGuzman commented on src/components/__tests__/CustomListSearchFormContent-test.tsx
> +    setSelectedLanguage = stub();
I think you can/should also test these `set` functions that are passed. Even if they don't update a local variable, that they are called appropriately.

2021-12-01 15:49 UTC, oliviawongnyc commented on src/components/CustomListSearchAdvancedOptions.tsx
> +  );
I would have thought the same thing, but I tested it out and for this particular data, which is nested, the options without concat lead to a 2-dimensional array, and the code requires a flat array.

2021-12-01 15:52 UTC, oliviawongnyc commented on src/components/CustomListSearchAdvancedOptions.tsx
> +            {/* eslint-disable-next-line jsx-a11y/no-onchange */}
No, this line is here because of an outdated rule that says to use onBlur instead of onChange for select tags. [More info here](https://books.google.com/books?id=5fo8EAAAQBAJ&pg=PT383&lpg=PT383&dq=disable+jsx-a11y/no-onchange&source=bl&ots=gRnZmXpyAu&sig=ACfU3U3KhHe0NaEKwVD19l-OYnx4kGNdpQ&hl=en&sa=X&ved=2ahUKEwjsw7_o98L0AhUMZzABHeCcBkMQ6AF6BAgWEAM#v=onepage&q=disable%20jsx-a11y%2Fno-onchange&f=false), if you're curious.

2021-12-01 15:54 UTC, oliviawongnyc commented on src/components/CustomListSearchFormContent.tsx
> +              {!entryPoints.includes("All") && (
Done!

2021-12-01 20:17 UTC, oliviawongnyc commented on src/components/__tests__/CustomListSearchAdvancedOptions-test.tsx
> +});
I added functions to test that the set functions are called onChange. Does this work?

2021-12-02 16:41 UTC, EdwinGuzman commented on src/components/CustomListSearchAdvancedOptions.tsx
> +  );
What about just `const languagesToMap = languageFields?.map(....);` ?

2021-12-02 16:41 UTC, EdwinGuzman approved these changes
Updated tests look good. I'd err on the side of more tests, even for prop functions, until you can move to RTL.

2021-12-03 16:10 UTC, samanthaandrews commented on src/components/CustomListSearch.tsx
> +  console.log("entryPoints -->", entryPoints);
Stray console.log here

2021-12-03 16:17 UTC, samanthaandrews commented on src/components/CustomListSearch.tsx
> +  console.log("entryPoints -->", entryPoints);
nvm ignore me looking at outdated code!!

2021-12-07 16:09 UTC, merged